version: "3"

vars:
  IMAGE: docker.io/library/nginx:alpine
  NAME: personal-site-dev
  PORT: "8080"

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  dev:
    desc: Run NGINX dev container with live mounts (Podman)
    cmds:
      - |
        podman run --replace -d --name "{{.NAME}}" -p "{{.PORT}}:80" \
          -v ./site/pages:/usr/share/nginx/html:Z \
          -v ./site/nginx.conf:/etc/nginx/conf.d/default.conf:Z \
          "{{.IMAGE}}"

  stop:
    desc: Stop and remove the dev container if it exists (Podman)
    silent: true
    cmds:
      - podman rm -f "{{.NAME}}" >/dev/null 2>&1 || true
