# Dev environment values for personal-site
replicaCount: 3

ingress:
  enabled: true
  className: "istio"
  name: "personal-site-dev-ingress"
  annotations:
    kubernetes.io/ingress.class: istio
    cert-manager.io/cluster-issuer: cloudflare-dns01
  hosts:
    - host: jwhiteaker.homelab.kubesoar.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: personal-site-dev-tls
      hosts:
        - jwhiteaker.homelab.kubesoar.com

podDisruptionBudget:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app: personal-site

networkPolicies:
  - name: default-deny
    podSelector: {}
    policyTypes:
      - Ingress
      - Egress
  - name: allow-ingress
    podSelector:
      matchLabels:
        app: personal-site
    policyTypes:
      - Ingress
    ingress:
      - ports:
          - protocol: TCP
            port: 3000
  - name: allow-dns
    policyTypes:
      - Egress
    egress:
      - to:
          - namespaceSelector: {}
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
