# Dev environment values for personal-site
replicaCount: 1

ingress:
  enabled: true
  className: "istio"
  name: "personal-site-dev-ingress"
  annotations:
    kubernetes.io/ingress.class: istio
    cert-manager.io/cluster-issuer: cloudflare-dns01
  hosts:
    - host: jwhiteaker.homelab.kubesoar.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: personal-site-dev-tls
      hosts:
        - jwhiteaker.homelab.kubesoar.com

podDisruptionBudget:
  enabled: false
