apiVersion: v1
kind: Namespace
metadata:
  name: personal-site
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
    openshift.io/display-name: "Personal Site (Production)"
    openshift.io/description: "Production environment for Personal Website workloads"
