apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-quota
  namespace: personal-site
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  hard:
    pods: "30"
