apiVersion: v1
kind: ResourceQuota
metadata:
  name: services-quota
  namespace: personal-site
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  hard:
    services: "10"
    services.nodeports: "0"
    services.loadbalancers: "2"
