apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: personal-site-dev-envs
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  limits:
    - type: Pod
      min:
        cpu: 25m
        memory: 32Mi
      max:
        cpu: "4"
        memory: 4Gi
