apiVersion: v1
kind: ResourceQuota
metadata:
  name: memory-quota
  namespace: personal-site-runners
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  hard:
    requests.memory: 16Gi
    limits.memory: 32Gi
