apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: personal-site-runners
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: 50Gi
