apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-quota
  namespace: personal-site-dev-envs
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  hard:
    requests.cpu: "4"
    limits.cpu: "8"
