apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: personal-site
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  limits:
    - type: Container
      default:
        cpu: 1000m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "4"
        memory: 4Gi
