apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: personal-site-runners
  labels:
    app.kubernetes.io/part-of: personal-website-app
    app.kubernetes.io/managed-by: github-actions
spec:
  limits:
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 20Gi
