name: Pull Request - Helm Unit Tests

on:
  pull_request:
    branches: [main, master]
    paths:
      - "charts/**"
      - ".github/workflows/pr-helm-unit-tests.yaml"
  workflow_dispatch:

jobs:
  helm-test:
    name: Lint and Unit Test Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: latest

      - name: Lint Helm Chart
        run: |
          helm lint charts/personal-site

      - name: Install helm-unittest Plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git --verify=false

      - name: Run Helm Unit Tests
        run: |
          helm unittest charts/personal-site
